// Code generated by goctl. DO NOT EDIT.
package types

type UpdateRequestWithoutVersion struct {
	Hostnameport  string `json:"hostnameport"`
	Queryparamter string `json:"queryparamter"`
}

type Request struct {
	ApiVersion    string `path:"apiversion"`
	Hostnameport  string `path:"hostnameport"`
	Queryparamter string `path:"queryparamter"`
}

type UpdateRequest struct {
	ApiVersion    string `path:"apiversion"`
	Hostnameport  string `json:"hostnameport"`
	Queryparamter string `json:"queryparamter"`
}

type BatchUpdateRequest struct {
	ApiVersion string                        `path:"apiversion"`
	Requests   []UpdateRequestWithoutVersion `json:"requests"`
}

type Response struct {
	Message string `json:"message"`
}
