// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"urlinfo/urlinfo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Tokenlimit},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/urlinfo/:apiversion/:hostnameport/:queryparamter",
					Handler: UrlLookupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/urlinfo/:apiversion/update",
					Handler: UrlUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/urlinfo/:apiversion/batchupdate",
					Handler: UrlBatchUpdateHandler(serverCtx),
				},
			}...,
		),
	)
}
